"""empty message

Revision ID: 0f4a6c4d36c4
Revises: c79ab96aaac4
Create Date: 2019-02-23 20:38:11.200355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4a6c4d36c4'
down_revision = 'c79ab96aaac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo_creator', table_name='todo')
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['creator_id'], ['id'])
    op.drop_column('todo', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('creator', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['creator'], ['id'])
    op.create_index('ix_todo_creator', 'todo', ['creator'], unique=False)
    # ### end Alembic commands ###
