"""empty message

Revision ID: 160ccbd87f3b
Revises: 47cda3460b9b
Create Date: 2019-02-23 21:06:41.078262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160ccbd87f3b'
down_revision = '47cda3460b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('creator', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator'], ['id'])

    # ### end Alembic commands ###
