"""empty message

Revision ID: 5ed02d755c5d
Revises: 160ccbd87f3b
Create Date: 2019-02-23 21:07:36.141208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed02d755c5d'
down_revision = '160ccbd87f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_foreign_key('creator', 'user', ['creator'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator'], ['id'])

    # ### end Alembic commands ###
