"""empty message

Revision ID: 7bdf8fc6c8db
Revises: ba3123c9650c
Create Date: 2019-02-23 20:47:51.407577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdf8fc6c8db'
down_revision = 'ba3123c9650c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('creator', 'todo', 'user', ['creator'], ['username'])
    op.drop_column('todo', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('creator_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###
