"""empty message

Revision ID: ba3123c9650c
Revises: 91b5d6d01bba
Create Date: 2019-02-23 20:45:09.120322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3123c9650c'
down_revision = '91b5d6d01bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['creator'], ['username'])
    op.drop_column('todo', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('creator_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###
