"""empty message

Revision ID: c79ab96aaac4
Revises: baa799e0a434
Create Date: 2019-02-23 20:30:33.491264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79ab96aaac4'
down_revision = 'baa799e0a434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_todo_creator'), 'todo', ['creator'], unique=False)
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['creator'], ['id'])
    op.drop_index(op.f('ix_todo_creator'), table_name='todo')
    op.drop_column('todo', 'creator_id')
    # ### end Alembic commands ###
