"""empty message

Revision ID: d1f42d033f0b
Revises: 7bdf8fc6c8db
Create Date: 2019-02-23 20:48:43.196120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f42d033f0b'
down_revision = '7bdf8fc6c8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_foreign_key('creator', 'user', ['creator'], ['username'])
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator'], ['id'])

    # ### end Alembic commands ###
